### ISSUE TITLE
Orphan Issues tracker

### ISSUE THREAD

**Issue by heysokam** [OpensourceQuake3/defrag#43]
Tracks any issue that doesn't have a parent patch yet.
- [ ] Find a name for the `v0.5.0` patch
- [ ] _#todo: Complete the list of TODO features_
- [ ] Remove this from `v0.5.0` milestone when the above #todo list is completed
