### ISSUE TITLE
[wishlist] Tracker for desirable features that are currently not prioritized

### ISSUE THREAD

**Issue by heysokam** [OpensourceQuake3/defrag#5]
> Reminder: This is not a todo. It's a wishlist
### General
- [ ] Airjump Powerup
- [ ] Physics selection Powerups (cpm and vq3 sections in the same map)
- [ ] Client sided logic (EntityPlus and SourceEngine-I/O inspired)
- [ ] Gamemodes:
  - [ ] Native race mode (like AG, first to finish wins. also FFA race, standings based on finish order)
  - [ ] PVP race mode (can interact with other players, and do things to change their movement)
  - [ ] Timed Duel maps : Pick all key items to set a time (like ctf, but for duel maps instead)
- [ ] Look-behind command (map-based, not global)
- [ ] Improved replay tools (q3mme inspired, using the new UI tools)
- [ ] New data and stats:
  - [ ] Persistent stats per map.
  - [ ] Checkpoints: player vs wr, p vs pb (spec or own), p vs own pb
  - [ ] Getting data from leaderboards server to compare
- [ ] Ghosts expand:
  - [ ] Multiple ghosts (example: own & spec'ed player)
- [ ] Conditional binds (bind X if cvar cvarvalue actionTrue actionFalse)
- [ ] Improved Loading screen:
  - [ ] Adjust thumbnail based on resolution
  - [ ] Better map info distribution
  - [ ] Add map description text field
- [ ] Separate respawn command
- [ ] 0ups Teleport property
- [ ] Improved networking
  - [ ] serverside rollback
  - [ ] clientside prediction for projectiles
  - [ ] predicted explosions

### New physics
- [x] vq1 movement (qw/ag)
  - [x] AD movement
    - [x] QW balanced
    - [x] AG balanced
  - [x] Baby Jumps (aka Duckroll)
  - [x] SBJ
  - [ ] Q1 rocket launcher
  - [ ] Gaus (needs new name)
  - [ ] ...
- [ ] vq2 movement
- [x] vq4 movement
- [ ] New mechanics
  - [ ] Walljumps (urt insp) (optional wsw-like powerup, to boost its power)
  - [ ] ...

### Others
- [ ] Vortex weapons (implosion/pull instead of explosion/knockback)
- [ ] Portals
- [ ] Steam integration (requires Standalone game, since we are not modding baseq3 but gpl code)

### Fixes
- [ ] Make target_speaker loop globally (currently can either loop or global, but not both)
- [ ] Solve issues with clip/slick/trigger brush rendering. transparency, render limit, impossible to hide some brushes from gameplay
